name: Deploy Next.js App to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install Dependencies and Build
    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build
      working-directory: ./spa

    # Step 3: Setup SSH
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 4: Deploy Build Artifacts to Server
    - name: Deploy Next.js Build
      run: |
        cd spa
        tar -czf next.tar.gz .next
        scp -o StrictHostKeyChecking=no next.tar.gz ${{ secrets.USER }}@${{ secrets.SERVER_IP }}:/var/www/html/rstation.ddns.net
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /var/www/html/rstation.ddns.net
        tar -xzf next.tar.gz
        rm next.tar.gz
        pm2 restart app-name || pm2 start npm --name "app-name" -- start
        EOF
