name: Deploy Next.js App to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install Dependencies and Build the Next.js App
    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build
      working-directory: ./spa

    # Step 3: Deploy Build Artifacts to Server
    - name: Deploy Build Artifacts
      run: |
        # Compress the .next directory
        tar -czf next.tar.gz .next
        # Securely copy the tar.gz file to the server
        scp -o StrictHostKeyChecking=no ./next.tar.gz ${{ secrets.USER }}@${{ secrets.SERVER_IP }}:/path/to/deployment/directory
        # SSH into the server and extract files
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /path/to/deployment/directory
        tar -xzf next.tar.gz
        rm next.tar.gz
        pm2 restart app-name || pm2 start npm --name "app-name" -- start
        EOF
      working-directory: ./spa